// <auto-generated />
using System;
using Axe.TaskManagement.Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axe.TaskManagement.Data.Migrations
{
    [DbContext(typeof(AxeTaskManagementDbContext))]
    [Migration("20241114102510_UpdateTableInbox")]
    partial class UpdateTableInbox
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gin");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axe.TaskManagement.Model.Entities.ExtendedInboxIntegrationEvent", b =>
                {
                    b.Property<Guid>("IntergrationEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<Guid?>("DocInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityIds")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityInstanceIds")
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventBusIntergrationEventCreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventBusIntergrationEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExchangeName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ProjectInstanceId")
                        .HasColumnType("uuid");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint");

                    b.Property<string>("ServiceInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ServiceInstanceIdProcessed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("VirtualHost")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("IntergrationEventId", "ServiceCode");

                    b.ToTable("ExtendedInboxIntegrationEvents", "public");
                });

            modelBuilder.Entity("Ce.Constant.Lib.Dtos.OutboxIntegrationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("EntityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExchangeName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServiceInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("OutboxIntegrationEvents", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
